src/main/default/objects/Sandbox_User__mdt/Sandbox_User__mdt.object-meta.xml
<CustomObject>
    <label>Sandbox User</label>
    <pluralLabel>Sandbox Users</pluralLabel>
</CustomObject>

src/main/default/objects/Sandbox_User__mdt/fields/Base_Username__c.field-meta.xml
<CustomField>
    <fullName>Base_Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <inlineHelpText>This is used create a sandbox user with a username in the form of &quot;Base_Username.Sandbox_Name&quot;.</inlineHelpText>
    <label>Base Username</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Sandbox_User__mdt/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

src/main/default/classes/PrepareSandboxTest.cls
@isTest
class PrepareSandboxTest {

    private final static String SANDBOX_NAME = 'sbx';

    @isTest
    static void runApexClass_should_work() {
        // Count users
        Integer initialUserCount = database.countQuery('SELECT COUNT() FROM User');
        // Get sanbox users from custom metadata
        List<Sandbox_User__mdt> sbxUsers = [SELECT DeveloperName, Base_Username__c, Email__c FROM Sandbox_User__mdt];

        // Simulate sandbox copy
        Test.startTest();
        Test.testSandboxPostCopyScript(
            new PrepareSandbox(),
            UserInfo.getOrganizationId(),
            UserInfo.getOrganizationId(),
            SANDBOX_NAME
        );
        Test.stopTest();

        // Check that users were created
        Integer newUserCount = database.countQuery('SELECT COUNT() FROM User');
        System.assertEquals(newUserCount, initialUserCount + sbxUsers.size());
        
        // Check that at least one user has the right username and the admin profile
        if (sbxUsers.size() > 0) {
            User sbxUser = [SELECT Username, Profile.Name FROM User ORDER BY CreatedDate DESC LIMIT 1];
            String expectedUsername = sbxUsers[sbxUsers.size() -1].Base_Username__c +'.'+ SANDBOX_NAME;
            System.assertEquals(sbxUser.Username, expectedUsername);
            System.assertEquals(sbxUser.Profile.Name, 'System Administrator');
        }
    }
}